#!/bin/bash

set -e

: "${DEPLOY_STAGE:?Need to set DEPLOY_STAGE}"
: "${DEPLOY_KEY:?Need to set DEPLOY_KEY}"

now=$(date +%Y-%m-%dT%H:%M:%S%z)
sha=$(git rev-parse --short HEAD)

echo "\"Deployed\" ${sha} to ${DEPLOY_STAGE} at ${now}"